name: Java CI Deploy Jar App to AWS S3

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build with Maven
      run: mvn clean install

    - name: Rename JAR with versioning
      run: |
        TIMESTAMP=$(date +%Y%m%d%H%M%S)
        mv target/api-joueurs-0.0.1.jar target/api-joueurs-${TIMESTAMP}.jar
        echo "JAR_NAME=api-joueurs-${TIMESTAMP}.jar" >> $GITHUB_ENV

    - name: Archive build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: jar-artifact
        path: target/*.jar

    - name: Upload to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1' # Replace with your AWS region
      run: aws s3 cp target/${{ env.JAR_NAME }} s3://app-legendesfootball/${{ env.JAR_NAME }}

  #deploy:
    #needs: build
    #runs-on: ubuntu-latest

    #steps:
    #- name: Checkout code
      #uses: actions/checkout@v2

   # - name: Download build artifacts
    #  uses: actions/download-artifact@v2
    #  with:
     #   name: jar-artifact
     #   path: .

   # - name: Deploy to AWS EC2
    #  env:
      #  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       # AWS_REGION: 'us-east-1' # Replace with your AWS region
      #  EC2_HOST: ${{ secrets.EC2_HOST }}
      #  JAR_NAME: ${{ env.JAR_NAME }}
     # run: |
        #echo "${{ secrets.EC2_SSH_KEY }}" > ec2-gdb-aws.pem
      #  chmod 400 ec2-gdb-aws.pem
        # Debugging step to check if the key file is correctly created
       # ls -l ec2-gdb-aws.pem
       # cat ec2-gdb-aws.pem
       # ssh -i ec2-gdb-aws.pem -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
        #  aws s3 cp s3://app-legendesfootball/${JAR_NAME} /home/ec2-user/${JAR_NAME}
        #  pkill -f 'java -jar' || true
         # nohup java -jar /home/ec2-user/${JAR_NAME} > /home/ec2-user/app.log 2>&1 &
      #  EOF
